vich_uploader:
    db_driver: orm
    mappings:
        upload_img:
            uri_prefix: '%upload_img%'
            upload_destination: '%kernel.project_dir%/public/image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
